RESTfulWebApi/RESTfulWebApi/Models/EventModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RESTfulWebApi.Models
{
    public class EventModel
    {
        public Guid Id { get; set; }
        [DisplayName("Nome")]
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data de Inicio")]
        public DateTime? StartingDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data de Fim")]
        public DateTime? EndingDate { get; set; }
        [DisplayName("Descrição")]
        public string Description { get; set; }
        [DisplayName("Criador")]
        public string Creator { get; set; }
        public bool IsCreation { get; set; }
    }
}

RESTfulWebApi/RESTfulWebApi/Controllers/EventManagerController.cs
using Entities.Events;
using Newtonsoft.Json;
using RESTfulWebApi.Helpers;
using RESTfulWebApi.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RESTfulWebApi.Controllers
{
    public class EventManagerController : Controller
    {
        // GET: Events
        public ActionResult Events()
        {
            var events = GetEvents();
            ViewBag.Events = events;
            ViewBag.HasEvents = events.Count() > 0;
            return View("Events");
        }

        public ActionResult Create()
        {
            return View("Edit", new EventModel() { IsCreation = true });
        }

        public ActionResult Edit(Guid id)
        {
            var evt = GetEvent(id);
            ((EventModel)evt).IsCreation = false;
            return View(evt);
        }

        public ActionResult Info(Guid id)
        {
            var evt = GetEvent(id);
            ViewBag.Event = evt;
            return View("Event");
        }

        private object GetEvent(Guid value)
        {
            var client = new RequestBuilder("Events");
            return ConvertToEventModel(client.GetObject<EventDTO>(value));
        }

        public ActionResult DeleteEvent(EventModel evt)
        {
            var client = new RequestBuilder("Events");
            client.DeleteObject(evt.Id);

            return RedirectToAction("Events");
        }

        public ActionResult About()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveEvent(EventModel model)
        {
            var evtDTO = ConvertToEventDTO(model);
            var client = new RequestBuilder("Events");
            EventDTO result = null;
            EventModel newModel = null;

            if (model.IsCreation)
            {
                result = client.PostObject<EventDTO>(evtDTO);
            }
            else
            {
                result = client.PutObject<EventDTO>(evtDTO, model.Id);
            }

            newModel = ConvertToEventModel(result);
            newModel.IsCreation = false;

            return RedirectToAction("Edit", new { id = newModel.Id });
        }

        private IEnumerable<EventModel> GetEvents()
        {
            var client = new RequestBuilder("Events");

            return client.GetObject<List<EventDTO>>().Select(x => ConvertToEventModel(x));
        }

        private EventModel ConvertToEventModel(IEvent evt)
        {
            return new EventModel()
            {
                Id = evt.Id,
                Creator = evt.Creator,
                Description = evt.Description,
                EndingDate = evt.EndingDate,
                Name = evt.Name,
                StartingDate = evt.StartingDate,
            };
        }

        private EventDTO ConvertToEventDTO(EventModel evt)
        {
            return new EventDTO()
            {
                Id = evt.Id,
                Creator = evt.Creator,
                Description = evt.Description,
                EndingDate = evt.EndingDate,
                Name = evt.Name,
                StartingDate = evt.StartingDate,
            };
        }
    }
}

RESTfulWebApi/RESTfulWebApi/Views/EventManager/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Shared/_layout.cshtml";
}

<h2>Sobre este sistema</h2>

REST (REpresentational State Transfer) é um estilo de arquitetura para sistemas de hipermídia distribuídos, como a World Wide Web, que é definido por um conjunto de restrições com características específicas:
<ul>
    <li>Baseado em Recursos</li>
    <li>Interface uniforme</li>
    <li>Sem estado (stateless)</li>
    <li>Recursos nomeados em forma de localizador</li>
    <li>Arquitetura Cliente-Servidor</li>
</ul>

Esse sistema foi desenvolvido utilizando .NET, MVC 5.0 (C#) e Microsoft SQL Server. 

RESTfulWebApi/RESTfulWebApi/Views/EventManager/Edit.cshtml
@model RESTfulWebApi.Models.EventModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Shared/_layout.cshtml";
}
@if (Model.IsCreation)
{
    <h2>Criar Novo Evento</h2>
}
else
{
    <h2>Editar Evento "@Model.Name"</h2>
}

@using (Html.BeginForm("SaveEvent", "EventManager", FormMethod.Post))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.StartingDate, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.StartingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.EndingDate, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.EndingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.IsCreation);

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @if (Model.IsCreation)
    {
        @Html.ActionLink("Voltar", "Events", null , new { @class = "btn btn-primary" })
    }
    else
    {
        @Html.ActionLink("Voltar", "Info", new { id = Model.Id }, new { @class = "btn btn-primary" })
    }
</div>

<script>
    $(function () {
        $("#StartingDate").datepicker({ dateFormat: 'dd/mm/yy' });
        $("#EndingDate").datepicker({ dateFormat: 'dd/mm/yy' });
    });
</script>

RESTfulWebApi/RESTfulWebApi/Views/EventManager/Event.cshtml
@using RESTfulWebApi.Models

@{
    ViewBag.Title = "Event";
    Layout = "~/Shared/_layout.cshtml";
}

@{ 
    var evt = (EventModel)ViewBag.Event;
}

<div class="col-md-4 col-md-offset-4">
    <div class="thumbnail">
        <div class="caption-full">
            <h4 class="pull-left">
                Início:
                @if (evt.StartingDate.HasValue)
                {
                    @evt.StartingDate.Value.ToShortDateString()
                }
                else
                {
                    <text>Sem Data de Início </text>
                }
            </h4>

            <h4 class="pull-right">
                Fim:
                @if (evt.EndingDate.HasValue)
                {
                    @evt.EndingDate.Value.ToShortDateString()
                }
                else
                {
                    <text>Sem Data de Fim</text>
                }
            </h4>
            <br />
            <h3>
                <a href="">@evt.Name</a>
            </h3>
            <p>@evt.Description</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    @Html.ActionLink("Voltar", "Events", new { id = "" }, new { @class = "pull-left btn icon-btn btn-primary" })
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Editar", "Edit", new { id = evt.Id }, new { @class = "btn icon-btn btn-success" })
                    @Html.ActionLink("Apagar", "DeleteEvent", new { id = evt.Id }, new { @class = "btn icon-btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
</div>

RESTfulWebApi/RESTfulWebApi/Views/EventManager/Events.cshtml
@using RESTfulWebApi.Models

@{
    ViewBag.Title = "Events";
    Layout = "~/Shared/_layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                @if ((bool)ViewBag.HasEvents)
                {
                    foreach (EventModel evt in ViewBag.Events)
                    {
                        <div class="col-sm-4 col-lg-4 col-md-4">
                            <div class="thumbnail">
                                <div class="caption">
                                    <h4 class="pull-right">
                                        Início:
                                        @if (evt.StartingDate.HasValue)
                                        {
                                            @evt.StartingDate.Value.ToShortDateString()
                                        }
                                        else
                                        {
                                            <text>Sem Data de Início</text>
                                        }
                                    </h4>


                                    <h4>
                                        @Html.ActionLink(evt.Name, "Info", new { id = evt.Id })
                                    </h4>
                                    <p>@evt.Description</p>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <text>Nenhum Evento Cadastrado</text>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-5">
                <a href="~/EventManager/Events/Create" class="btn btn-primary">Criar Evento</a>
            </div>
        </div>
    </div>
</div>